# Generated by Django 5.0.3 on 2024-04-28 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KnowledgeSetModel',
            new_name='KnowledgeInfoModel',
        ),
    ]
