# Generated by Django 5.0.3 on 2024-04-28 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_rename_knowledgeinfomodel_knowledgeinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KnowledgeInfo',
            new_name='KnowledgeInfoModel',
        ),
    ]
