FROM ubuntu:22.04

RUN sed -i 's/archive.ubuntu.com/tw.archive.ubuntu.com/g' /etc/apt/sources.list
RUN apt update && \
    apt upgrade -y && \
    apt install -y python3-pip

RUN ln -s /usr/bin/python3 /usr/bin/python
RUN adduser --disabled-password demo

COPY ./frontend /streamlit
COPY ./requirements/frontend /streamlit/requirements

RUN pip3 install pip -U && \
    pip install -r /streamlit/requirements --no-cache-dir

RUN chown -R demo:demo /streamlit

USER demo
WORKDIR /streamlit

CMD ["streamlit", "run", "chat.py"]
